.TH COUNT_FILES 1 "October 2026" "count-files 2.0"
.SH NAME
count_files \- count files in a directory
.SH SYNOPSIS
.B count_files
[DIRECTORY] [EXTENSION]
.SH DESCRIPTION
Counts regular files, directories and symbolic links
in the given directory. Default values are taken from
/etc/count-files.conf
.SH OPTIONS
.TP
.B \-h
Show help and exit.
.SH AUTHOR
Illia Brui
